name: Website Change Monitor

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 requests

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run website monitor
      env:
        TARGET_URL: ${{ secrets.TARGET_URL }}
        LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python monitor.py

    - name: Commit changes if hash updated
      run: |
        if [ -f previous_hash.txt ]; then
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add previous_hash.txt
          git commit -m "Update website hash" || echo "No changes to commit"
          git push
        fi
